GET http://localhost:3000/citations

###

GET http://localhost:3000/citations/1

### Create a product
POST http://localhost:3000/citations/
Content-Type: application/json

{
    "frase": "la vita è bella",
    "valore": 150,
    "id": 7
}

### Delete a product
DELETE http://localhost:3000/api/v1/products/5